src/views/settings.py
import datetime

from flask import Blueprint, render_template, redirect, request, url_for, flash

from src import db
from src.utils.genarators import Getters, TransactionUpdate
from src.utils.system import SystemUtil
from src.utils.user_profile import Profile
from src.models.account_type_model import AccountType
from src.models.bank_table_model import Banks
from src.models.branch_model import Branch
from src.models.transaction_charge_fee_model import TransactionChargeFee

settings = Blueprint('settings', __name__)


@settings.route('/add_tran_type/', methods=['POST', 'GET'])
def add_tran_type():
    if request.method == 'POST':
        tran_type = str.upper(request.form['tran_type'])
        tran_charge = float(request.form['tran_charge'])
        new = TransactionChargeFee(tran_type=tran_type,
                                   tran_charge=tran_charge)
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('settings.system_setting'))
    else:
        return render_template('settings/add_trans_type.html', user=Profile().user_details())


@settings.route('/del_tran_type/<int:tid>/')
def del_tran_type(tid):
    trans_id = int(tid)

    record = db.session.query(TransactionChargeFee).filter_by(id=trans_id).first()
    db.session.delete(record)
    db.session.commit()
    flash('Transaction Type Record Deleted')
    return redirect(url_for('settings.system_setting'))


@settings.route('/add_acc_type/', methods=['POST', 'GET'])
def add_acc_type():
    if request.method == 'POST':
        acc_type = str.capitalize(request.form['acc_type'])
        min_balance = int(request.form['min_balance'])
        new = AccountType(acc_type=acc_type,
                          minbalance=min_balance)
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('settings.system_setting'))
    else:
        return render_template('settings/add_acc_type.html', user=Profile().user_details())


@settings.route('/del_acc_type/<int:id>/')
def del_acc_type(id):
    tid = id
    record = db.session.query(AccountType).filter_by(id=tid).first()
    db.session.delete(record)
    db.session.commit()
    return redirect(url_for('settings.system_setting'))


@settings.route('/add_branch/', methods=['POST', 'GET'])
def add_branch():
    if request.method == 'POST':
        code = request.form['branch_code']
        description = request.form['description']
        date = datetime.datetime.now()
        new = Branch(code=code,
                     description=description,)
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('settings.system_setting'))
        pass
    else:
        return render_template('settings/add_branch.html', user=Profile().user_details())


@settings.route('/del_branch/<int:id>/', methods=['POST', 'GET'])
def del_branch(id):
    record = db.session.query(Branch).filter_by(id=id).first()
    db.session.delete(record)
    db.session.commit()
    return redirect(url_for('settings.system_setting'))


@settings.route('/add_bank/', methods=['POST', 'GET'])
def add_bank():
    if request.method == 'POST':
        name = request.form['name']
        swift_code = str.upper(request.form['swift_code'])
        new = Banks(name=name,
                    swift_code=swift_code)
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('settings.system_setting'))
    else:
        return render_template('settings/add_bank.html', user=Profile().user_details())


@settings.route('/delete_bank/<int:id>/', methods=['POST', 'GET'])
def delete_bank(id):
    record = db.session.query(Banks).filter_by(id=id).first()
    db.session.delete(record)
    db.session.commit()
    return redirect(url_for('settings.system_setting'))


@settings.route('/system_setting/')
def system_setting():
    return render_template('settings/system_settings.html', user=Profile().user_details(),
                           tran=TransactionUpdate.getTransationTypeCharge(), acct=Getters.getAccountType(),
                           branch=SystemUtil.get_system_branches(), banks=SystemUtil.get_registered_banks(), currency=SystemUtil.get_system_currencies())


@settings.route('/user_setting/')
def user_setting():
    return render_template('settings/user_settings.html', user=Profile().user_details())


@settings.route('/information_setting/')
def information_setting():
    return render_template('settings/information_settings.html', user=Profile().user_details())

src/templates/settings/add_acc_type.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Systems Settings
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>System</li>
        <li class="active">Add Account Type</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </section>
    <section class="content">
        <div>
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <ul class="alert alert-warning" role="alert">
                {% for message in messages %}
                  <p style="position: relative;">{{ message }}</p>
                {% endfor %}
                </ul>
               {% endif %}
            {% endwith %}
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-warning">
                        <div class="box-header">Add Account Type</div>
                        <form method="POST" action="{{ url_for('settings.add_acc_type') }}">
                            <div class="box-body">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Account Type</span>
                                <input class="form-control" id="acc_type" name="acc_type" type="text" aria-describedby="sizing-addon3" autofocus required>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Minimum Balance</span>
                                <input class="form-control" id="min_balance" name="min_balance" type="number" aria-describedby="sizing-addon3" required>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <button class="btn btn-primary form-control"  type="submit">Submit</button>
                            </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



</div>
{%  endblock %}

src/templates/settings/add_bank.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Systems Settings
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>System</li>
        <li class="active">Add Bank</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </section>
    <section class="content">
        <div>
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <ul class="alert alert-warning" role="alert">
                {% for message in messages %}
                  <p style="position: relative;">{{ message }}</p>
                {% endfor %}
                </ul>
               {% endif %}
            {% endwith %}
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-warning">
                        <div class="box-header">Add Bank</div>
                        <form method="POST" action="{{ url_for('settings.add_bank') }}">
                            <div class="box-body">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Bank</span>
                                <input class="form-control" id="branch_code" name="name" type="text" aria-describedby="sizing-addon3" autofocus required>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Swift Code</span>
                                <input class="form-control" id="description" name="swift_code" type="text" aria-describedby="sizing-addon3" required>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <button class="btn btn-primary form-control"  type="submit">Submit</button>
                            </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



</div>
{%  endblock %}

src/templates/settings/add_branch.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Systems Settings
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>System</li>
        <li class="active">Add Branch</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </section>
    <section class="content">
        <div>
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <ul class="alert alert-warning" role="alert">
                {% for message in messages %}
                  <p style="position: relative;">{{ message }}</p>
                {% endfor %}
                </ul>
               {% endif %}
            {% endwith %}
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-warning">
                        <div class="box-header">Add Branch</div>
                        <form method="POST" action="{{ url_for('settings.add_branch') }}">
                            <div class="box-body">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Branch Code</span>
                                <input class="form-control" id="branch_code" name="branch_code" type="text" aria-describedby="sizing-addon3" autofocus>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Description</span>
                                <input class="form-control" id="description" name="description" type="text" aria-describedby="sizing-addon3">
                            </div><br>
                            <div class="input-group input-group-sm">
                                <button class="btn btn-primary form-control"  type="submit">Submit</button>
                            </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



</div>
{%  endblock %}

src/templates/settings/add_trans_type.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Systems Settings
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>System</li>
        <li class="active">Add Transaction Type</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </section>
    <section class="content">
        <div>
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <ul class="alert alert-warning" role="alert">
                {% for message in messages %}
                  <p style="position: relative;">{{ message }}</p>
                {% endfor %}
                </ul>
               {% endif %}
            {% endwith %}
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-warning">
                        <div class="box-header">Add Transation Type</div>
                        <form method="POST" action="{{ url_for('settings.add_tran_type') }}">
                            <div class="box-body">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Trans Type</span>
                                <input class="form-control" id="tran_type" name="tran_type" type="text" aria-describedby="sizing-addon3" autofocus>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Charge</span>
                                <input class="form-control" id="tran_charge" name="tran_charge" type="text" aria-describedby="sizing-addon3">
                            </div><br>
                            <div class="input-group input-group-sm">
                                <button class="btn btn-primary form-control"  type="submit">Submit</button>
                            </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



</div>
{%  endblock %}

src/templates/settings/information_settings.html
{% extends 'base.html' %}

{% block content %}


{%  endblock %}

src/templates/settings/system_settings.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Systems Settings
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">System</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </section>
    <section class="content">
        <div>
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <ul class="alert alert-warning" role="alert">
                {% for message in messages %}
                  <p style="position: relative;">{{ message }}</p>
                {% endfor %}
                </ul>
               {% endif %}
            {% endwith %}
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <div class="box box-warning">
                        <div class="box-header">Account Type</div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Type</th>
                                    <th>Min Bal</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in acct %}
                                <tr>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.acc_type }}</td>
                                    <td>{{ i.minbalance }}</td>
                                    <td><a href="{{ url_for('settings.del_acc_type', id=i.id) }}">Delete</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    <div class="box-footer"><a href="{{ url_for('settings.add_acc_type') }}"> Add</a></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box box-danger">
                        <div class="box-header">Transaction Type</div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Type</th>
                                    <th>Charge</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in tran %}
                                <tr>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.tran_type }}</td>
                                    <td>{{ i.tran_charge }}</td>
                                    <td><a href="{{ url_for('settings.del_tran_type', tid=i.id) }}">Delete</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="box-footer"><a href="{{ url_for('settings.add_tran_type') }}"> Add</a></div>
                    </div>
                </div>
            <div class="col-md-4">
                    <div class="box box-danger">
                        <div class="box-header">Transaction Type</div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Code</th>
                                    <th>Description</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in branch %}
                                <tr>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.code }}</td>
                                    <td>{{ i.description }}</td>
                                    <td><a href="{{ url_for('settings.del_branch', id=i.id) }}">Delete</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="box-footer"><a href="{{ url_for('settings.add_branch') }}"> Add</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-warning">
                        <div class="box-header">Banks</div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Swift Code</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in banks %}
                                <tr>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.name }}</td>
                                    <td>{{ i.swift_code }}</td>
                                    <td><a href="{{ url_for('settings.delete_bank', id=i.id) }}">Delete</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="box-footer"><a href="{{ url_for('settings.add_bank') }}"> Add</a></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-warning">
                        <div class="box-header">Currency</div>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Currency</th>
                                <th>Description</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in currency %}
                                <tr>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.currency_code }}</td>
                                    <td>{{ i.description }}</td>
                                    <td><a href="#">Delete</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="box-footer"><a href="#"> Add</a></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<div class="clearfix"></div>
</div>
{%  endblock %}

src/templates/settings/user_settings.html
{% extends 'base.html' %}

{% block content %}


{%  endblock %}