src/views/banking.py
import time

from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask import session as login_session

from src import db
from src.utils.Enums import TransactionType
from src.utils.genarators import Getters, TransactionUpdate, Auto
from src.utils.system import SystemUtil
from src.utils.transactions import AccountTransaction, ChargeTransaction
from src.utils.user_profile import Profile
from src.models.bank_table_model import Banks
from src.models.customer_model import Customer
from src.utilities.search import Search
from src.utilities.verifier import Verify

banking = Blueprint('banking', __name__)


@banking.route('/dep_account_search/', methods=['post', 'get'])
def account_search():
    if request.method == 'POST':
        acc_num = int(request.form['account_number'])
        record = Search.search_by_account(acc_num)
        if record is not None:
            return render_template('banking/deposits.html', record=record, user=Profile().user_details())
        else:
            flash('The Account Number Provided Is NOT In The System')
            return render_template('banking/deposits.html', record=record, user=Profile().user_details())
    else:
        return redirect(url_for('banking.deposits'))


@banking.route('/deposits/', methods=['POST', 'GET'])
def deposits():
    record = None
    if request.method == 'POST':
        if Verify.till_is_linked(login_session['username']):
            cr_account_number = int(request.form['client_account'])
            if Verify.account_exists(cr_account_number):
                system_date = Getters.getSysDate().date  # use system date for transactions
                dep_ref = request.form['deposit_ref']
                amount = float(request.form['deposit_amount'])

                AccountTransaction(date=system_date, amount=amount, cr_account=cr_account_number).deposit(dep_ref)

                TransactionUpdate.ttUpdate(TransactionType.DEBIT, amount, system_date, dep_ref, cr_account_number)
                flash('Account Credited')
                return redirect(url_for('banking.deposits', user=Profile().user_details()))
            else:
                flash('Account Cannot be found: Search again')
                return redirect(url_for('banking.deposits', user=Profile().user_details()))
        else:
            flash('User is NOT linked to Any Till. Please Open a Till First')
            return redirect(url_for('banking.deposits'))
    else:
        return render_template('banking/deposits.html', record=record, user=Profile().user_details())


@banking.route('/stmt_search/', methods=['post', 'get'])
def stmt_search():
    dt = Getters.getSysDate().date  # time.strftime('%Y-%m-%d')
    start_date = ''
    end_date = ''
    if request.method == 'POST':
        acc_num = int(request.form['account_number'])
        start_date = request.form['start_date']
        end_date = request.form['end_date']

        record, statement_records = Search.search_stmt_transactions(acc_num, start_date, end_date)

        if record is not None and statement_records:
            return render_template('banking/statement.html', record=record, stmt=statement_records, dt=dt,
                                   sd=start_date, ed=end_date, user=Profile().user_details())
        else:
            flash('The Account Number Provided Is NOT In The System')
            return render_template('banking/statement.html', record=record, stmt=statement_records, dt=dt,
                                   sd=start_date, ed=end_date, user=Profile().user_details())
    else:
        return redirect(url_for('banking.statement', dt=dt, sd=start_date, ed=end_date, user=Profile().user_details()))


@banking.route('/stmt_print/<account>/<start_date>/<end_date>')
def stmt_print(account, start_date, end_date):
    dt = Getters.getSysDate().date  # time.strftime('%Y-%m-%d')
    acc_num = int(account)
    start_date = start_date
    end_date = end_date
    # record = session.query(Customer).filter_by(acc_number=acc_num).first()
    record, statement_records = Search.search_stmt_transactions(acc_num, start_date, end_date)
    return render_template('banking/stmt_printed.html', record=record, stmt=statement_records, dt=dt, sd=start_date,
                           ed=end_date, user=Profile().user_details())


@banking.route('/statement/')
def statement():
    start_date, end_date = '', ''
    date_time = time.strftime('%Y-%m-%d')
    return render_template('banking/statement.html', record=None, stmt=[], dt=date_time, sd=start_date, ed=end_date,
                           user=Profile().user_details())


@banking.route('/transfer_search/', methods=['POST', 'GET'])
def transfer_search():
    if request.method == 'POST':
        from_account = request.form['from_account']
        to_account = request.form['to_account']
        if from_account == to_account:
            flash('The Accounts submitted are the same')
            return redirect(url_for('banking.transfer'))

        if Verify.account_exists(from_account):
            if Verify.account_exists(to_account):
                record = [from_account, to_account]
                return render_template('banking/transfer.html', user=Profile().user_details(), record=record,
                                       fad=Getters.getCustomerAccountDetails(from_account),
                                       tad=Getters.getCustomerAccountDetails(to_account))
            else:
                flash('To Account number is not valid')
                return redirect(url_for('banking.transfer'))
        else:
            flash('from account is not valid')
            return redirect(url_for('banking.transfer'))


@banking.route('/transfer/', methods=['POST', 'GET'])
def transfer():
    if request.method == 'POST':
        from_acc = request.form['from_acc']
        to_acc = request.form['to_acc']
        remark = request.form['remark']
        amount = float(request.form['amount'])
        if amount > Getters.getCustomerAccountDetails(from_acc).working_bal:
            flash('The Account ' + from_acc + ' has no overdraft facility ')
            return redirect(url_for('banking.transfer'))
        else:
            TransactionUpdate.transferTransactionUpdate(from_acc, to_acc, amount, remark, Getters.getSysDate().date)
            # TransactionUpdate.accChargeUpdate('TR', from_acc, Getters.getSysDate().date)
            ChargeTransaction(Getters.getSysDate().date, from_acc).charges(TransactionType.TRANSFER)

            flash('Transfer Successful')
            return redirect(url_for('banking.transfer'))
    else:
        record = []
        fad = None
        tad = None
        return render_template('banking/transfer.html', user=Profile().user_details(), record=record, fad=fad, tad=tad)


@banking.route('/external_transfer_search/', methods=['post', 'get'])
def external_transfer_search():
    if request.method == 'POST':
        acc_num = int(request.form['from_account'])
        if db.session.query(Customer).filter_by(acc_number=acc_num).first():
            record = db.session.query(Customer).filter_by(acc_number=acc_num).first()
            return render_template('banking/external_transfer.html', record=Getters.getCustomerAccountDetails(acc_num),
                                   user=Profile().user_details(),
                                   banks=SystemUtil.get_registered_banks(), fad=Getters.getCustomerAccountDetails(acc_num))
        else:
            flash('The Account Number Provided Is NOT In The System')
            record = None
            return render_template('banking/deposits.html', record=record, user=Profile().user_details(),
                                   banks= SystemUtil.get_registered_banks())
    else:
        return redirect(url_for('banking.deposits'))


@banking.route('/external_transfer/', methods=['POST', 'GET'])
def external_transfer():
    if request.method == 'POST':
        from_acc = request.form['from_acc']
        to_bank = request.form['to_bank']
        swift = db.session.query(Banks).filter_by(name=to_bank).first()
        swift_code = swift.swift_code
        to_ext_acc = request.form['to_ext_acc']
        remark = request.form['remark']
        remark += " " + str(swift_code)
        amount = float(request.form['amount'])
        if amount > Getters.getCustomerAccountDetails(from_acc).working_bal:
            flash('Account Balance is Less than Required')
            return redirect(url_for('banking.external_transfer'))
        else:
            TransactionUpdate.externalTransferTransactionUpdate(from_acc, to_ext_acc, amount, remark,
                                                                Getters.getSysDate().date)

            # TransactionUpdate.accChargeUpdate('RTGS', from_acc, Getters.getSysDate().date)
            ChargeTransaction(Getters.getSysDate().date, from_acc).charges(TransactionType.RTGS)
            flash('RTGS Successful')
            return redirect(url_for('banking.external_transfer'))
    else:
        record = []
        # fad = From Account Details
        # tad = To Account Details
        fad = None
        tad = None
        return render_template('banking/external_transfer.html', fad=fad, tad=tad, record=record,
                               user=Profile().user_details(), banks=SystemUtil.get_registered_banks())


@banking.route('/with_account_search/', methods=['post', 'get'])
def with_account_search():
    if request.method == 'POST':
        acc_num = int(request.form['account_number'])
        record = Search.search_by_account(acc_num)
        if record is not None:
            return render_template('banking/withdrawal.html', record=record, user=Profile().user_details())
        else:
            flash('The Account Number Provided Is NOT In The System')
            return render_template('banking/withdrawal.html', record=record, user=Profile().user_details())

        # if session.query(Customer).filter_by(acc_number=acc_num).first():

src/views/enquiry.py
from flask import Blueprint, render_template

from src.utils.genarators import Getters
from src.utils.user_profile import Profile

enquiry = Blueprint('enquiry', __name__)


@enquiry.route('/account_reset/')
def account_reset():
    record = []
    return render_template('enquiry/account_reset.html', record=record, user=Profile().user_details())


@enquiry.route('/stmt_drill_down/<ft_reference>')
def stmt_drill_down(ft_reference):
    # record = []
    record = Getters.getTransactionDetails(ft_reference)
    return render_template('enquiry/stmt_drilldown.html', record=record, user=Profile().user_details())

src/templates/banking/deposits.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Deposits
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Deposits</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">

            <div class="row">
                <div class="col-md-4">
                    <form method="post" action="{{ url_for('banking.account_search') }}">
                    <div class="box box-info">
                        <div class="box-header">Search Account</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Account:</span>
                            <input class="form-control" id="account_number" name="account_number" type="number" aria-describedby="sizing-addon3" autofocus required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div>
                        {% with messages = get_flashed_messages() %}
                          {% if messages %}
                            <ul class="alert alert-danger" role="alert">
                            {% for message in messages %}
                              <p style="position: relative;">{{ message }}</p>
                            {% endfor %}
                            </ul>
                           {% endif %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="col-md-12">
            <div class="row">

                <div class="col-md-6">
                    <form method="post" action="{{ url_for('banking.deposits') }}">

                    <div class="box box-danger">
                        <div class="box-header">Deposit</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Depositor Ref</span>
                            <input class="form-control" id="deposit_ref" name="deposit_ref" type="text" aria-describedby="sizing-addon3" autofocus>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Amount</span>
                            <input class="form-control" id="deposit_amount" name="deposit_amount" type="text" aria-describedby="sizing-addon3">
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Client Account</span>
                            <input class="form-control" id="client_account" name="client_account" value="{{ record.acc_number }}" type="number" aria-describedby="sizing-addon3">
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="col-md-6">
                    <div class="box box-danger">
                        <div class="box-header">Client Account Details</div>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>Name</dt>
                                <dd>{{ record.first_name }} {{ record.last_name }}</dd>
                                <dt>Date of Birth</dt>
                                <dd>{{ record.dob }}</dd>
                                <dt>Address</dt>
                                <dd>{{ record.address }}</dd>
                                <dt>Country</dt>
                                <dd>{{ record.country }}</dd>
                                <dt>Email</dt>
                                <dd>{{ record.email }}</dd>
                                <dt>Gender</dt>
                                <dd>{{ record.gender }}</dd>
                                <dt>Phone</dt>
                                <dd>{{ record.contact_number }}</dd>
                                <dt>Balance</dt>
                                <dd>{{ record.working_bal }}</dd>
                                <dt>------------------</dt>
                                <dd>------------------</dd>
                                <dt>Account</dt>
                                <dd>{{ record.acc_number }}</dd>
                                <dt>Account Type</dt>
                                <dd>{{ record.account_type }}</dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
{% endblock %}

src/templates/banking/external_transfer.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Externale Transfer
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">External Transfer</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
        <div class="col-md-12">
            <div class="row">
                <form method="POST" action="{{ url_for('banking.external_transfer_search') }}">
                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header">Verify From Accounts</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3"><b>From</b> Account:</span>
                            <input class="form-control" id="from_account" name="from_account" type="number" aria-describedby="sizing-addon3" required autofocus>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header">......</div>
                    </div>
                </div>
                </form>
                <div class="col-md-4">
                    <div>
                        {% with messages = get_flashed_messages() %}
                          {% if messages %}
                            <ul class="alert alert-danger" role="alert">
                            {% for message in messages %}
                              <p style="position: relative;">{{ message }}</p>
                            {% endfor %}
                            </ul>
                           {% endif %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="clearfix" style="width: 100%;height: 120px; color: midnightblue"></div>
    <section class="content">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-danger">
                        <div class="box-header">Transaction Amounts</div>
                        <div class="box-body">
                            <form method="POST" action="{{ url_for('banking.external_transfer') }}">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">From Acc</span>
                                <input class="form-control" id="from_acc" name="from_acc" type="number" value="{{ record.acc_number }}" aria-describedby="sizing-addon3">
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Bank</span>
                                <select class="form-control" name="to_bank">
                                    <option></option>
                                    {% for i in banks %}
                                        <option>{{ i.name }}</option>
                                    {% endfor %}
                                </select>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Ext Bank Acc</span>
                                <input class="form-control" id="to_ext_acc" name="to_ext_acc" type="number"  aria-describedby="sizing-addon3">
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Transfer Ref</span>
                                <input class="form-control" id="remark" name="remark" type="text" aria-describedby="sizing-addon3" autofocus>
                            </div><br>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">Amount</span>
                                <input class="form-control" id="amount" name="amount" type="number" aria-describedby="sizing-addon3">
                            </div><br>
                            <div class="input-group input-group-sm">
                                <button class="btn btn-primary form-control"  type="submit">Submit</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-danger">
                        <div class="box-header">Transfer Account Brief Details</div>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>from Acc Name</dt>
                                <dd>{{ fad.first_name }}{{ fad.last_name }}</dd>
                                <dt>Account Number</dt>
                                <dd>{{ fad.acc_number }}</dd>
                                <dt>Available Balance</dt>
                                <dd>{{ fad.working_bal }}
                                <dt>Signature</dt>
                                <dd>{{ record.signature }}</dd>
                                <dt>---</dt>
                                <dd>---</dd>
                                <br>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
{% endblock %}

src/templates/banking/statement.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper" style="min-height: 626px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Statement
                <small>...</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Statement</li>
            </ol>
        </section>
        <section class="content-header">
            <div class="col-md-12">

                <div class="row">
                    <div class="col-md-4">
                        <form method="post" action="{{ url_for('banking.stmt_search') }}">
                            <div class="box box-info">
                                <div class="box-header">Search Account</div>
                                <div class="input-group input-group-sm">
                                    <span class="input-group-addon" id="sizing-addon3">Account:</span>
                                    <input class="form-control" id="account_number" name="account_number" type="number"
                                           aria-describedby="sizing-addon3" autofocus required>
                                </div>
                                <br>
                                <div class="input-group input-group-sm">
                                    <button class="btn btn-primary form-control" type="submit">Submit</button>
                                </div>
                            </div>

                    </div>
                    <div class="col-md-4">
                        <div class="box box-info">
                            <div class="box-header">Date Range</div>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">from :</span>
                                <input class="form-control" id="start_date" name="start_date" type="date"
                                       aria-describedby="sizing-addon3" required>
                            </div>
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon" id="sizing-addon3">To :</span>
                                <input class="form-control" id="end_date" name="end_date" type="date"
                                       aria-describedby="sizing-addon3" required>
                            </div>
                            <br>
                        </div>
                        </form>
                    </div>
                    <div class="col-md-4">
                        <div>
                            {% with messages = get_flashed_messages() %}
                                {% if messages %}
                                    <ul class="alert alert-danger" role="alert">
                                        {% for message in messages %}
                                            <p style="position: relative;">{{ message }}</p>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                </div>
            </div>

        </section>
        <div class="clearfix" style="width: 100%;height: 120px; color: midnightblue"></div>
        <!-- Main content -->
        <section class="invoice">
            <!-- title row -->
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-header">
                        <i class="fa fa-globe"></i> Open Banking System, Inc.
                        <small class="pull-right">Date: {{ dt }}</small>
                    </h2>
                </div>
                <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                    <address>
                        <strong>Open Banking System, Inc.</strong><br>
                        1237 Falcon Street<br>
                        Suite 23 Samlevies Village<br>
                        Borrowdale<br>
                        Email: info@obs.co.zw
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <address>
                        <strong>{{ record.first_name }} {{ record.last_name }}</strong><br>
                        {{ record.address }}<br>
                        {{ record.country }}<br>
                        Phone: {{ record.contact_number }}<br>
                        Email: {{ record.email }}
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">

                    <br>
                    <b>from Date:</b>{{ sd }}<br>
                    <b>To Date:</b> {{ ed }}<br>
                    <b>Account:</b> {{ record.acc_number }}
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- Table row -->
            <div class="row">
                <div class="col-xs-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Tran Type</th>
                            <th>Amount</th>
                            <th>Ref</th>
                            <th>Remark</th>
                            <th>Current Balance</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in stmt %}
                            <tr>
                                <td>{{ i.tran_date }}</td>
                                <td>{{ i.trantype }}</td>
                                <td>${{ i.amount }}</td>
                                <td>
                                    <a href="{{ url_for('enquiry.stmt_drill_down', ft_reference=i.tranref) }}">{{ i.tranref }}</a>
                                </td>
                                <td>{{ i.remark }}</td>
                                <td>${{ i.current_balance }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>

                            <td><b>Balance as at: </b></td>
                            <td><b>{{ ed }}</b></td>
                            <td><b>${{ record.working_bal }}</b></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- /.row -->

            <!-- this row will not appear when printing -->
            <div class="row no-print">
                <div class="col-xs-12">
                    {% if record == None %}
                        <a href="#" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>
                    {% else %}
                        <a href="{{ url_for('banking.stmt_print', account=record.acc_number,start_date=sd,end_date=ed) }}" target="_blank"
                           class="btn btn-default"><i class="fa fa-print"></i> Print</a>
                    {% endif %}
                    <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
                        <i class="fa fa-download"></i> Generate PDF
                    </button>
                </div>
            </div>
        </section>
        <div class="clearfix"></div>


        <!-- /.content -->
    </div>
{% endblock %}