src/forms/user_forms.py
"""
    forms.user_forms
    ----------------

    forms for user input fields verifications and validation etc

"""

from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

from src import db
from src.forms import (FlaskForm, StringField, PasswordField, SubmitField, BooleanField, IntegerField, SelectField,
                       FileField, FileAllowed)
from src.models.system_user_model import SystemUser


# from src.models.models import User


class RegistrationsForm(FlaskForm):
    """
    form class for user registrations
    """
    fullname = StringField('Username', validators=[DataRequired(), Length(min=4)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=5)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    ts_and_cs = BooleanField('Agree to ')
    submit = SubmitField('Register')

    def validate_email(self, email):
        """
        This method evaluates on submission if the user with the same email exists. if so a
        validation error is sent.
        :param email:
        :return: ValidationError
        """
        user = db.session.query(SystemUser).filter_by(email=email.data).first()
        if user:
            raise ValidationError("This email already exists. Please try a different one.")


class LoginForm(FlaskForm):
    """
    form class for user login.
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=5)])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Login')


class LockScreenForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), Length(min=5)])
    submit = SubmitField('Login')


class UserProfileForm(FlaskForm):
    """
    form class for user profile edit.
    """
    full_name = StringField('Full Name', validators=[DataRequired(), Length(min=4)])
    job_title = StringField('Job Title')
    department = StringField('Department')
    branch_code = SelectField('Branch Code', validators=[DataRequired()])
    access_level = IntegerField('Access level', validators=[DataRequired()])
    image_string = FileField('Image', validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

src/views/user.py
from flask import Blueprint, render_template, redirect, url_for, flash

from src.forms.user_forms import RegistrationsForm, LoginForm, UserProfileForm, LockScreenForm
from src.viewmodels.user_view_model import get_all_branches, login_handler, \
    LoginState, process_logout, process_lock_screen, process_register, process_edit_profile, get_profile_user_details

user_view = Blueprint('user_view', __name__)


# bcrypt = Bcrypt()


@user_view.route('/lockscreen/', methods=['post', 'get'])
def lockscreen():
    form = LockScreenForm()

    state = process_lock_screen(form)
    if state[0] == LoginState.SHOW_DASHBOARD:
        return redirect(url_for('dashboard_view.home'))
    elif state[0] == LoginState.SHOW_LOGIN_LOCKSCREEN:
        flash("Wrong Password try again", "danger")
        return redirect(url_for('user_view.lockscreen'))
    elif state[0] == LoginState.SHOW_LOCKSCREEN:
        return render_template('user/lockscreen.html', user=state[1], form=form)


@user_view.route('/', methods=['POST', 'GET'])
def login():
    """
    This function handles the login requests by the user. it takes in the email and password as
    input parameters
    :return: template and form
    """
    form = LoginForm()

    state = login_handler(form)
    if state == LoginState.SHOW_LOGIN:
        return render_template('user/login.html', form=form)
    elif state == LoginState.SHOW_LOGIN_LOCKED:
        flash('User is locked, Contact Systems Administrator', 'danger')
        return redirect(url_for('user_view.login'))
    elif state == LoginState.SHOW_LOGIN_INCORRECT_PASSWORD:
        flash('Password is Incorrect', 'danger')
        return redirect(url_for('user_view.login'))
    elif state == LoginState.SHOW_LOGIN_EMAIL_NOT_EXIST:
        flash('Email does not exist', 'warning')
        return redirect(url_for('user_view.login'))
    elif state == LoginState.SHOW_DASHBOARD:
        return redirect(url_for('dashboard_view.home'))


@user_view.route('/register', methods=['POST', 'GET'])
def register():
    """
    this function handles the registration of a new user
    :return:
        render_template and form
    """
    form = RegistrationsForm()
    state = process_register(form)
    if state == LoginState.SHOW_LOGIN:
        flash('User Successfully Registered', 'success')
        return redirect(url_for('user_view.login'))
    elif state == LoginState.SHOW_REGISTER:
        return render_template('user/register.html', form=form)


@user_view.route('/logout/')
def logout():
    state = process_logout()
    if state == LoginState.SHOW_LOGOUT:
        flash("Logged Out", "success")
        return redirect(url_for('user_view.login'))
    else:
        flash('Already Logged Off', 'warning')
        return redirect(url_for('user_view.login'))


#
# def allowed_file(filename):
#     return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@user_view.route('/edit_user/', methods=['POST', 'GET'])
def edit_profile():
    form = UserProfileForm()

    state = process_edit_profile(form)
    if state == LoginState.SHOW_USER_PROFILE:
        return redirect(url_for('user_view.profile', user=get_profile_user_details()))
    elif state == LoginState.SHOW_USER_EDIT_PROFILE:
        return render_template('user/edit_user.html', user=get_profile_user_details(), branch=get_all_branches(),
                               form=form)


@user_view.route('/admin')
def test_admin():
    return render_template('user/test_admin.html')


@user_view.route('/profile/')
def profile():
    return render_template('user/profile.html', user=get_profile_user_details())

src/views/user_view_model.py
import os
import random
import string
from enum import Enum
from typing import List, Tuple, Any

from flask import session
from PIL import Image

from src.controller.base_repository import BaseRepository
from src.controller.user_controller import UserController
from src.forms.user_forms import LoginForm, LockScreenForm, RegistrationsForm, UserProfileForm
from src.models.branch_model import Branch
from src.models.system_user_model import SystemUser
from src.views.user_repository import UserRepository

# UPLOAD_FOLDER = os.path.abspath("src/static/img/user///")
UPLOAD_FOLDER = os.path.abspath("/Users/trustmubaiwa/PycharmProjects/OBS/src/static/img/user///")

user_repository = UserRepository()
base_repository = BaseRepository()


class LoginState(Enum):
    SHOW_LOGIN = 0
    SHOW_LOGIN_INCORRECT_PASSWORD = 1
    SHOW_LOGIN_EMAIL_NOT_EXIST = 2
    SHOW_LOGIN_LOCKED = 3
    SHOW_DASHBOARD = 4
    SHOW_LOGOUT = 5
    SHOW_LOGOUT_ALREADY = 6
    SHOW_LOGIN_LOCKSCREEN = 7
    SHOW_LOCKSCREEN = 8
    SHOW_REGISTER = 9
    SHOW_USER_PROFILE = 10
    SHOW_USER_EDIT_PROFILE = 11


def get_profile_user_details() -> SystemUser:
    return user_repository.query_system_user()


def get_all_branches() -> List[Branch]:
    return base_repository.get_branches()


def _get_user_details_by_email(email: str) -> SystemUser:
    return user_repository.query_system_user(email)


def _get_current_system_user() -> SystemUser:
    return user_repository.query_system_user()


def update_user_login_session(user: SystemUser, username: str) -> None:
    session['username'] = username
    user.lock = 1
    user_repository.query_update_user(user)


def _generate_random_key(length):
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(length))


def save_image(form_picture):
    """
    saves the form_picture object with new randomly generated name and scales the image to 125 x 125 using
    the Pillow image library

    params:
        form_picture: is an object of type <class 'werkzeug.datastructures.FileStorage'>
    return:
        a string for the new image filename
    """
    random_hex = _generate_random_key(8)

    _, f_ext = os.path.splitext(form_picture.filename)
    image_filename = random_hex + f_ext

    image_path = os.path.join(UPLOAD_FOLDER, image_filename)

    output_size = (125, 125)
    resize_image = Image.open(form_picture)
    resize_image.thumbnail(output_size)
    resize_image.save(image_path)
    return image_filename


def process_edit_profile(form: UserProfileForm):
    form.branch_code.choices = [(t.code, t.description) for t in get_all_branches()]
    if form.validate_on_submit():
        image_file = ''
        if form.image_string.data:
            image_file = save_image(form.image_string.data)

        user = user_repository.query_system_user()
        user_controller = UserController(email=user.email,
                                         password='blank',
                                         full_name=form.full_name.data,
                                         job_title=form.job_title.data,
                                         image_string=image_file,
                                         department=form.department.data,
                                         branch_code=form.branch_code.data,
                                         access_level=form.access_level.data)
        user_controller.update_user()
        return LoginState.SHOW_USER_PROFILE
    return LoginState.SHOW_USER_EDIT_PROFILE


def _set_user_lock_state(lock: bool, user: SystemUser) -> None:
    user.lock = 1 if lock else 0
    user_repository.query_update_user(user)


def process_lock_screen(form: LockScreenForm) -> tuple[LoginState, Any]:
    user_account: SystemUser = user_repository.query_system_user()

    if form.validate_on_submit():
        password = form.password.data

        user_instance = UserController(full_name=user_account.full_name, email=user_account.email, password=password)

        if user_instance.verify_password():
            _set_user_lock_state(True, user_account)
            return LoginState.SHOW_DASHBOARD, None
        else:
            return LoginState.SHOW_LOGIN_LOCKSCREEN, None
    else:
        _set_user_lock_state(False, user_account)
        return LoginState.SHOW_LOCKSCREEN, user_account


def process_login(form: LoginForm) -> LoginState:
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user_instance = UserController(email=email, password=password)
        if user_instance.verify_email():
            user_account = _get_user_details_by_email(email)

            if user_account.lock == 1:  # Checker.userDbSession(email):
                return LoginState.SHOW_LOGIN_LOCKED
            else:
                if user_instance.verify_password():
                    update_user_login_session(user_account, email)
                    return LoginState.SHOW_DASHBOARD
                else:
                    return LoginState.SHOW_LOGIN_INCORRECT_PASSWORD
        else:
            return LoginState.SHOW_LOGIN_EMAIL_NOT_EXIST

    return LoginState.SHOW_LOGIN


def process_logout() -> LoginState:
    if 'username' in session:
        user_account = user_repository.query_system_user()
        _set_user_lock_state(False, user_account)
        session.pop('username', None)
        return LoginState.SHOW_LOGOUT
    else:
        return LoginState.SHOW_LOGOUT_ALREADY


def process_register(form: RegistrationsForm) -> LoginState:
    if form.validate_on_submit():
        full_name = form.fullname.data
        email = form.email.data
        password = form.password.data
        ts_and_cs = form.ts_and_cs.data
        user_controller = UserController(full_name=full_name, email=email, password=password)
        user_controller.add_new_user()
        return LoginState.SHOW_LOGIN
    else:
        return LoginState.SHOW_REGISTER

src/templates/user/edit_user.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper" style="min-height: 626px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Amend Customer
                <small>...</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Edit User</li>
            </ol>
        </section>
        <section class="content">
            <form class="form-group" action="" enctype="multipart/form-data" method="POST">
                {{ form.hidden_tag() }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="box box-primary">
                            <div class="box-header with-border"> Edit Profile</div>
                            <div class="input-group input-group-sm">
                                {% if form.full_name.errors %}
                                    {% for error in form.full_name.errors %}
                                        {{ form.full_name.label(class="input-group-addon", id="sizing-addon3") }}
                                        {{ form.full_name(class="form-control", value= user.full_name, placeholder= user.full_name) }}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% else %}
                                    {{ form.full_name.label(class="input-group-addon", id="sizing-addon3") }}
                                    {{ form.full_name(class="form-control", value= user.full_name, placeholder= user.full_name) }}
                                {% endif %}
                            </div>
                            <br>
                            <div class="input-group input-group-sm">
                                {% if form.job_title.errors %}
                                    {% for error in form.job_title.errors %}
                                        {{ form.job_title.label(class="input-group-addon", id="sizing-addon3") }}
                                        {{ form.job_title(class="form-control", id="job_title", value= user.job_title, placeholder= user.job_title) }}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% else %}
                                    {{ form.job_title.label(class="input-group-addon", id="sizing-addon3") }}
                                    {{ form.job_title(class="form-control", id="job_title", value= user.job_title, placeholder= user.job_title) }}
                                {% endif %}
                            </div>
                            <br>
                            <div class="input-group input-group-sm">
                                {% if form.department.errors %}
                                    {% for error in form.department.errors %}
                                        {{ form.department.label(class="input-group-addon", id="sizing-addon3") }}
                                        {{ form.department(class="form-control", id="department", value= user.department, placeholder=user.department) }}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% else %}
                                    {{ form.department.label(class="input-group-addon", id="sizing-addon3") }}
                                    {{ form.department(class="form-control", id="department", value= user.department, placeholder=user.department) }}
                                {% endif %}

                            </div>
                            <br>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box box-primary">
                            <div class="box-header with-border">...</div>
                            <div class="input-group input-group-sm">
                                {% if form.branch_code.errors %}
                                    {% for error in form.branch_code.errors %}
                                        {{ form.branch_code.label(class="input-group-addon", id="sizing-addon3") }}
                                        {{ form.branch_code(class="form-control") }}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% else %}
                                    {{ form.branch_code.label(class="input-group-addon", id="sizing-addon3") }}
                                    {{ form.branch_code(class="form-control") }}

                                {% endif %}
                            </div>
                            <br>
                            <div class="input-group input-group-sm">
                                {% if form.access_level.errors %}
                                    {% for error in form.access_level.errors %}
                                        {{ form.access_level.label(class="input-group-addon", id="sizing-addon3") }}
                                        {{ form.access_level(class="form-control", value= user.access_level, placeholder= user.access_level) }}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% else %}
                                    {{ form.access_level.label(class="input-group-addon", id="sizing-addon3") }}
                                    {{ form.access_level(class="form-control", value= user.access_level, placeholder= user.access_level) }}
                                {% endif %}

                            </div>
                            <br>
                            <div class="input-group input-group-sm">
                                {{ form.image_string.label(class="input-group-addon", id="sizing-addon3") }}
                                {{ form.image_string(class="form-control", value= user.image_string ) }}
                                {% if form.image_string.errors %}
                                    {% for error in form.image_string.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}

                            </div>
                            <br>
                            <div class="input-group input-group-sm">
                                {{ form.submit(class="btn btn-primary form-control") }}
                            </div>
                            <br>
                        </div>
                    </div>
                </div>
            </form>
        </section>


    </div>
{% endblock %}

src/templates/user/lockscreen.html
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OBS | Lockscreen</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition lockscreen">

<div style=" width: 50%; margin-right: auto; margin-left: auto; margin-top: 3%">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <ul class="alert alert-{{ category }}" role="alert">
                    <p style="position: relative; text-align: center;">{{ message }}</p>
                </ul>
            {% endfor %}`
        {% endif %}
    {% endwith %}
</div>

<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
    <div class="lockscreen-logo">
        <a href="#"><b>Open Banking System</b></a>
    </div>
    <!-- User name -->
    <div class="lockscreen-name">{{ user.full_name }}</div>

    <!-- START LOCK SCREEN ITEM -->
    <div class="lockscreen-item">
        <!-- lockscreen image -->
        <div class="lockscreen-image">
            <img src="/static/img/user/{{ user.image_string }}" alt="User Image">
        </div>
        <!-- /.lockscreen-image -->

        <!-- lockscreen credentials (contains the form) -->
        <form class="lockscreen-credentials" method="post" action="">
            {{ form.hidden_tag() }}
            <div class="input-group">
                {% if form.password.errors %}
                    {{ form.password(class="form-control", placeholder="Password") }}
                    {% for error in form.password.errors %}
                        <div class="help-block">
                            <span class="with-error" style="color: red;"><small>{{ error }}</small></span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form-control", placeholder="Password") }}
                {% endif %}

                <div class="input-group-btn">
                    {{ form.submit(class="btn") }}<i class="fa fa-arrow-right text-muted"></i>
                    {#                    <button type="button" class="btn"></button>#}
                </div>
            </div>
        </form>
        <!-- /.lockscreen credentials -->

    </div>
    <!-- /.lockscreen-item -->
    <div class="help-block text-center">
        Enter your password to retrieve your session
    </div>
    <div class="text-center">
        <a href="#">Or sign in as a different user</a>
    </div>
    <div class="lockscreen-footer text-center">
        Copyright © 2017 <b><a href="http://trustmub.pythonanywhere.com" class="text-black">Trust Athanas
        Studios</a></b><br>
        All rights reserved
    </div>
</div>
<!-- /.center -->

<!-- jQuery 2.2.3 -->
<script src="/static/plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="/static/js/bootstrap.min.js"></script>


</body>
</html>

src/templates/user/login.html
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OBS | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/static/plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">


<div style=" width: 50%; margin-right: auto; margin-left: auto; margin-top: 3%">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <ul class="alert alert-{{ category }}" role="alert">
                    <p style="position: relative; text-align: center;">{{ message }}</p>
                </ul>
            {% endfor %}`
        {% endif %}
    {% endwith %}
</div>

<!-- <div id="browserType">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 alert alert-warning">
            <p>The system is designed to work with the Chromium based browser engine.</p>
            <h3><a href="">Download Chrome Browser.</a></h3>
        </div>
    </div>
</div>
-->

<div class="login-box">
    <div class="login-logo">
        <a href="{{ url_for('dashboard_view.home') }}"><b>Open Banking </b>System</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group has-feedback">
                {% if form.email.errors %}
                    {{ form.email(class="form-control", placeholder="Email", autofocus=true ) }}
                    {% for error in form.email.errors %}
                        <div class="help-block">
                            <span class="with-error" style="color: red;"><small>{{ error }}</small></span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form-control", placeholder="Email", autofocus=true ) }}
                {% endif %}
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                {% if form.password.errors %}
                    {{ form.password(class="form-control", placeholder="Password") }}
                    {% for error in form.password.errors %}
                        <div class="help-block">
                            <span class="with-error" style="color: red;"><small>{{ error }}</small></span>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form-control", placeholder="Password") }}
                {% endif %}
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <div class="icheckbox_square-blue" aria-checked="false" aria-disabled="false"
                                 style="position: relative;">
                                {{ form.remember_me(class="iCheck-helper", style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);" ) }}
                                {#                                <input type="checkbox"#}
                                {#                                       style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">#}
                                <ins class="iCheck-helper"
                                     style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
                            </div>
                            {{ form.remember_me.label }}
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    {{ form.submit(class="btn btn-primary btn-block btn-flat") }}
                    {#          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>#}
                </div>
                <!-- /.col -->
            </div>
        </form>
        <!--
        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
            Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
            Google+</a>
        </div> -->
        <!-- /.social-auth-links -->

        <a href="#">I forgot my password</a><br>
        <a href="{{ url_for('user_view.register') }}" class="text-center">Register New User</a>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="/static/plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/static/plugins/iCheck/icheck.min.js"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });

    $(function () {

        let browserElement = document.getElementById("browserType");
        browserElement.style.visibility = "hidden";

        if (navigator.userAgent.indexOf("Chrome") !== -1) {
            browserElement.style.visibility = "hidden";
        }
        else if (navigator.userAgent.indexOf("Safari") !== -1) {
            browserElement.style.visibility = "visible";
        }

        else if ((navigator.userAgent.indexOf("MSIE") !== -1) || (!!document.documentMode === true)) {
            browserElement.style.visibility = "visible";
        }
    });
</script>


</body>
</html>

src/templates/user/test_admin.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test Admin</title>
</head>
<body>
<h1>Test Admin</h1>


</body>
</html>