src/views/customer.py
import time

from flask import Blueprint, render_template, redirect, request, url_for, flash

from src import db
from src.controller.customer import CustomerController
from src.utils.genarators import Auto, Getters
from src.utils.transactions import AccountTransaction
from src.utils.user_profile import Profile
from src.models.customer_model import Customer
from src.utilities.verifier import Verify

customer = Blueprint('customer', __name__)


@customer.route('/add_cus/', methods=['POST', 'GET'])
def add_cus():
    new_account = Auto().account_number_generator()
    # name = request.form['first_name']

    if request.method == 'POST':

        first_name = request.form['first_name']
        last_name = request.form['last_name']
        dob = request.form['dob']
        gender = request.form['gender']
        contact_number = request.form['contact_number']
        email = request.form['email']
        address = request.form['address']
        country = request.form['country']
        acc_number = request.form['acc_number']
        initial_deposit = request.form['working_bal']
        if initial_deposit == "":
            working_bal = float(0)
        else:
            working_bal = float(initial_deposit)
        account_type = request.form['account_type']

        CustomerController(first_name=first_name,
                           last_name=last_name,
                           dob=dob,
                           gender=gender,
                           contact_number=contact_number,
                           email=email,
                           address=address,
                           country=country,
                           new_account=new_account,
                           working_bal=working_bal,
                           account_type=account_type,
                           inputter_id=Profile().user_details().uid
                           ).create_customer()

        result = AccountTransaction(date=time.strftime('%Y-%m-%d'), amount=working_bal,
                                    cr_account=new_account).create_account()
        if result == 0:
            flash("account Creation Failed")
        else:
            flash("Account Created Successfully")

        return redirect(url_for('customer.my_cus'))
    else:
        return render_template('customer/add_cus.html', new_account=new_account, user=Profile().user_details(),
                               account=Getters.getAccountType())


@customer.route('/id_search/', methods=['post', 'get'])
def id_search():
    if request.method == 'POST':
        id_num = int(request.form['customer_id'])
        if db.session.query(Customer).filter_by(custid=id_num).first():
            record = db.session.query(Customer).filter_by(custid=id_num).first()
            return render_template('customer/amend_cus.html', record=record, user=Profile().user_details(),
                                   account=Getters.getAccountType())
        else:
            flash('The Customer System ID Provided Is NOT Valid')
            record = None
            return render_template('customer/amend_cus.html', record=record, user=Profile().user_details())
    else:
        flash('Failed to go through the IF STMT')
        return redirect(url_for('customer.amend_cus', user=Profile().user_details()))


@customer.route('/cus_account_search/', methods=['post', 'get'])
def account_search():
    if request.method == 'POST':
        acc_num = int(request.form['account_number'])
        if db.session.query(Customer).filter_by(acc_number=acc_num).first():
            record = db.session.query(Customer).filter_by(acc_number=acc_num).first()
            return render_template('customer/amend_cus.html', record=record, user=Profile().user_details(),
                                   account=Getters.getAccountType())
        else:
            flash('The Account Number Provided Is NOT In The System')
            record = None
            return render_template('customer/amend_cus.html', record=record, user=Profile().user_details())
    else:
        return redirect(url_for('customer.amend_cus', user=Profile().user_details()))


@customer.route('/amend_cus/', methods=['POST', 'GET'])
def amend_cus():
    record = None
    if request.method == 'POST':
        acc_num = int(request.form['acc_number'])
        if Verify.account_exists(acc_num):

            a_record = db.session.query(Customer).filter_by(acc_number=acc_num).one()
            if request.form['first_name'] == a_record.first_name:
                pass
            else:
                a_record.first_name = request.form['first_name']
            if request.form['last_name'] == a_record.last_name:
                pass
            else:
                a_record.last_name = request.form['last_name']
            if request.form['dob'] == a_record.dob:
                pass
            else:
                a_record.dob = request.form['dob']
            if request.form['gender'] == a_record.gender:
                pass
            else:
                a_record.gender = request.form['gender']
            if request.form['contact_number'] == a_record.contact_number:
                pass
            else:
                a_record.contact_number = int(request.form['contact_number'])
            if request.form['email'] == a_record.email:
                pass
            else:
                a_record.email = request.form['email']
            if request.form['address'] == a_record.address:
                pass
            else:
                a_record.address = request.form['address']
            if request.form['country'] == a_record.country:
                pass
            else:
                a_record.country = request.form['country']
            if request.form['account_type'] == a_record.account_type:
                pass
            else:
                a_record.account_type = request.form['account_type']
            a_record.create_date = a_record.create_date

            db.session.add(a_record)
            db.session.commit()
            return redirect(url_for('customer.my_cus', user=Profile().user_details()))
        else:
            flash('Account Cannot be modified, Search Again')
            record = None
            return redirect(url_for('customer.amend_cus'))
    else:
        return render_template('customer/amend_cus.html', record=record, user=Profile().user_details(),
                               account=Getters.getAccountType())


@customer.route('/authorise/')
def authorise_cus():
    return render_template('customer/authorise.html', user=Profile().user_details())


@customer.route('/my_cus/')
def my_cus():
    all_customer = db.session.query(Customer).all()
    return render_template('customer/my_cus.html', customer=all_customer, user=Profile().user_details())

src/templates/customer/add_cus.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Add Customer
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Add Customer </li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <form class="form-group" method="post" action="{{ url_for('customer.add_cus') }}">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">New Customer</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Name:</span>
                            <input class="form-control" id="first_name" name="first_name" type="text" aria-describedby="sizing-addon3" autofocus required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Surname:</span>
                            <input class="form-control" id="last_name" name="last_name" type="text" aria-describedby="sizing-addon3" required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">D.O.B</span>
                            <input class="form-control" id="dob" name="dob" type="date" aria-describedby="sizing-addon3" required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Gender</span>
                            <input class="form-control" id="gender" name="gender" type="text" aria-describedby="sizing-addon3" required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Phone:</span>
                            <input class="form-control" id="contact_number" name="contact_number" type="text" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">E-mail:</span>
                            <input class="form-control" id="email" name="email" type="email" aria-describedby="sizing-addon3" >
                        </div><br>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">...</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Address:</span>
                            <input class="form-control" id="address" name="address" type="text" aria-describedby="sizing-addon3" required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Country:</span>
                            <input class="form-control" id="country" name="country" type="text" aria-describedby="sizing-addon3" required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Account Number:</span>
                            <input class="form-control" id="acc_number" name="acc_number" type="number" aria-describedby="sizing-addon3">
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Balance:</span>
                            <input class="form-control" id="working_bal" name="working_bal" type="text" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Acc Type:</span>

                            <select class="form-control" name="account_type" required>
                                <option></option>
                                {% for i in account %}
                                <option>{{ i.acc_type }}</option>
                                {% endfor %}
                            </select>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                </div>
            </div>


        </form>
    </section>
    <!-- /.content -->
</div>
{% endblock %}

src/templates/customer/amend_cus.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Amend Customer
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Amend Customer</li>
      </ol>
    </section>

    <!-- Main content -->
    <div class="content-header" style="margin-bottom: 0">
        <div class="col-md-12">

            <div class="row">
                <div>
                {% with messages = get_flashed_messages() %}
                  {% if messages %}
                    <ul class="alert alert-danger" role="alert">
                    {% for message in messages %}
                      <p style="position: relative;">{{ message }}</p>
                    {% endfor %}
                    </ul>
                   {% endif %}
                {% endwith %}
                </div>
                <div class="col-md-4">
                    <form method="post" action="{{ url_for('customer.account_search') }}">
                    <div class="box box-info">
                        <div class="box-header with-border">Search Account</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Account:</span>
                            <input class="form-control" id="account_number" name="account_number" type="number" aria-describedby="sizing-addon3" autofocus required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="col-md-4">
                    <form method="post" action="{{ url_for('customer.id_search') }}">
                    <div class="box box-info">
                        <div class="box-header with-border">Search Customer Sys ID</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Customer ID</span>
                            <input class="form-control" id="customer_id" name="customer_id" type="number" aria-describedby="sizing-addon3" required>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header with-border">Search Customer Name</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Customer Name</span>
                            <input class="form-control" id="customer_name" name="customer_name" type="text" aria-describedby="sizing-addon3" disabled>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <form class="form-group" method="POST" action="{{ url_for('customer.amend_cus') }}">
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">New Customer</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Name:</span>
                            <input class="form-control" id="first_name" name="first_name" type="text" value="{{ record.first_name }}" placeholder="{{ record.first_name }}" aria-describedby="sizing-addon3" autofocus>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Surname:</span>
                            <input class="form-control" id="last_name" name="last_name" type="text" value="{{ record.last_name }}" placeholder="{{ record.last_name }}" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">D.O.B</span>
                            <input class="form-control" id="dob" name="dob" type="date" value="{{ record.dob }}" placeholder="{{ record.dob }}" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Gender</span>
                            <input class="form-control" id="gender" name="gender" type="text" value="{{ record.gender }}" placeholder="{{ record.gender }}" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Phone:</span>
                            <input class="form-control" id="contact_number" name="contact_number" type="text" value="{{ record.contact_number }}" placeholder="{{ record.contact_number }}" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">E-mail:</span>
                            <input class="form-control" id="email" name="email" type="email" value="{{ record.email }}" placeholder="{{ record.email }}" aria-describedby="sizing-addon3" >
                        </div><br>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-primary">
                        <div class="box-header with-border">...</div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Address:</span>
                            <input class="form-control" id="address" name="address" type="text" value="{{ record.address }}" placeholder="{{ record.address }}" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Country:</span>
                            <input class="form-control" id="country" name="country" type="text" value="{{ record.country }}" placeholder="{{ record.country }}" aria-describedby="sizing-addon3" >
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Account Number:</span>
                            <input class="form-control" id="acc_number" name="acc_number" type="number" value="{{ record.acc_number }}" placeholder="{{ record.acc_number }}" aria-describedby="sizing-addon3">
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Balance:</span>
                            <input class="form-control" id="working_bal" name="working_bal" type="text" value="{{ record.working_bal }}" placeholder="{{ record.working_bal }}" aria-describedby="sizing-addon3" disabled="disabled">
                        </div><br>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">Acc Type:</span>
                            <select class="form-control" name="account_type"  required>
                                <option>{{ record.account_type }}</option>
                                {% for i in account %}
                                <option>{{ i.acc_type }}</option>
                                {% endfor %}
                            </select>
                        </div><br>
                        <div class="input-group input-group-sm">
                            <button class="btn btn-primary form-control"  type="submit">Submit</button>
                        </div><br>
                    </div>
                </div>
            </div>


        </form>
    </section>
    <!-- /.content -->
  </div>
{% endblock %}

src/templates/customer/authorise.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper" style="min-height: 626px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Authorise
        <small>...</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Authorise</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info">
                        <div class="box-header">Unauthorised Users</div>
                        <li>Always logout or lock the screen when you leave your workstation</li>
                        <li>Ensure the till opening balance tallies with the cash in hand</li>
                        <li></li>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info">
                        <div class="box-header">Unauthorised Customers</div>
                        <li>Always logout or lock the screen when you leave your workstation</li>
                        <li>Ensure the till opening balance tallies with the cash in hand</li>
                        <li></li>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info">
                        <div class="box-header">Unauthorised Transfers</div>
                        <li>Always logout or lock the screen when you leave your workstation</li>
                        <li>Ensure the till opening balance tallies with the cash in hand</li>
                        <li></li>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info">
                        <div class="box-header">Unauthorised RTGS</div>
                        <li>Always logout or lock the screen when you leave your workstation</li>
                        <li>Ensure the till opening balance tallies with the cash in hand</li>
                        <li></li>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info">
                        <div class="box-header">Unauthorised Bulk Payments</div>
                        <li>Always logout or lock the screen when you leave your workstation</li>
                        <li>Ensure the till opening balance tallies with the cash in hand</li>
                        <li></li>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
<div class="clearfix"></div>
{% endblock %}

src/templates/customer/my_cus.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper" style="min-height: 626px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My Customer
                <small>...</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">My Customer</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="col-md-12">
                <div class="row">
                    <div>
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <ul class="alert alert-info" role="alert">
                                    {% for message in messages %}
                                        <p style="position: relative;">{{ message }}</p>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        {% endwith %}
                    </div>
                    <div class="col-md-12">
                        <div class="box box-info">
                            <div class="box-header">Warning</div>
                            <table class="table">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Surname</th>
                                    <th>Account number</th>
                                    <th>Working balance</th>
                                    <th>Acc Type</th>
                                    <th>inputter</th>
                                    <th>Create Date</th>
                                </tr>
                                {% for i in customer %}
                                    <tr>
                                        <td class="empty">{{ i.custid }}</td>
                                        <td class="empty">{{ i.first_name }}</td>
                                        <td class="empty">{{ i.last_name }}</td>
                                        <td class="empty">{{ i.acc_number }}</td>
                                        <td class="empty">{{ i.working_bal }}</td>
                                        <td class="empty">{{ i.account_type }}</td>
                                        <td class="empty">{{ i.inputter_id }}</td>
                                        <td class="empty">{{ i.create_date }}</td>

                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
        <div class="clearfix"></div>
    </div>
{% endblock %}